// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzGar5We085kY2EGDpsQ1d5nUr_EFvrq4',
    appId: '1:1087862828777:web:f27e80423ee2d1be840a78',
    messagingSenderId: '1087862828777',
    projectId: 'kophecy',
    authDomain: 'kophecy.firebaseapp.com',
    storageBucket: 'kophecy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArJJF87MFifmYoi8fI98N10kLYeQqSCHw',
    appId: '1:1087862828777:android:7b2164d788ea40fe840a78',
    messagingSenderId: '1087862828777',
    projectId: 'kophecy',
    storageBucket: 'kophecy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAcXCaRXEF-DpWfgpF8Ci3-6R_bqbh6Ws',
    appId: '1:1087862828777:ios:16147371f73adf42840a78',
    messagingSenderId: '1087862828777',
    projectId: 'kophecy',
    storageBucket: 'kophecy.appspot.com',
    iosClientId: '1087862828777-siqm7rf9luol4cspun1khsa8mvjv5li6.apps.googleusercontent.com',
    iosBundleId: 'com.deventhusiast.quotes',
  );
}
